#!/usr/bin/env bash
#transfer a file from client to server
if [ $# -lt 3 ]; 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -lt 4 ];
then
    scp -o SSH_STRICT_HOSTKEY_CHECKING=no "$1" "$3@$2":~/
else
    scp -o SSH_STRICT_HOSTKEY_CHECKING=no "$4" "$1" "$3@$2":~/
fi
