#!/usr/bin/env bash
#transfer a file from client to server
if [ $# -lt 3 ]; 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
file_path="$1"
ip="$2"
username="$3"
key_path="$4"
elif [ $# -lt 4 ];
then
    scp -o SSH_STRICT_HOSTKEY_CHECKING=no "$file_path" "$username@$ip":~/
else
    scp -o SSH_STRICT_HOSTKEY_CHECKING=no "$key_path" "$file_path" "$username@$ip":~/
fi
