#!/usr/bin/env bash
#transfer a file from client to server
if [ $# -lt 3 ]; 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
file_path="$1"
ip="$2"
username="$3"
export SSH_STRICT_HOSTKEY_CHECKING=no
elif [ $# -lt 4 ];
then
    scp -i "$file_path" "$username@$ip":~/
fi
key_path="$4"
else
    scp -i "$key_path" "$file_path" "$username@$ip":~/
fi
