#!/usr/bin/env bash
# custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '26i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '27i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
