#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy


server_config=\
"
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 517566-web-01 52.3.251.54:80 check
    server 517566-web-02 54.90.13.191:80 check
"


echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
