#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 517566-web-01 52.3.251.54:80 check
    server 517566-web-02 54.90.13.191:80 check
EOF

# Restart HAProxy to apply changes
systemctl restart haproxy
