#!/usr/bin/env bash
#Bash script that displays formatted content of /etc/passwd

IFS=$'\n'
while IFS= read -r line
do
    IFS=":" read -r ARRAY <<< "$line"
    echo "The user ${ARRAY[0]} is part of the ${ARRAY[4]} gang, lives in ${ARRAY[5]}, and rides ${ARRAY[6]}/${ARRAY[7]}. ${ARRAY[2]}'s place is protected by the passcode ${ARRAY[1]}, more info about the user here: ${ARRAY[0]}"
done < "/etc/passwd"
