#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r USERNAME PASSWORD User_ID_Info GROUP_ID GECOS HOME_DIRECTORY COMMAND
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $User_ID_Info's place is protected by the passcode $PASSWORD, more info about the user here: $GECOS"
done < "/etc/passwd"
